#!/bin/sh
# define running port
PORT=80

bash scripts/build
# start the pocketbase server on port 80
echo -e "\e[1;35m*** RUNNING POCKETBASE SERVER ON PORT $PORT ***\n\n"
go run PocketApp.go serve --http="0.0.0.0:$PORT"
