#!/bin/sh


# subshell so we don't have to cd ..
(
  cd react-app || exit
  npm run build
)

# remove old files in public dir
echo -e "\n\e[1;35m*** REMOVING POSSIBLY OUTDATED FILES IN PUBLIC DIRECTORY ***\n\n"
rm -r -d pb_public
# remake dir
mkdir pb_public
# copy contents from the react build
echo -e "\e[1;35m*** COPYING CONTENTS FROM NPM BUILD ***\n\n"
cp -a react-app/build/* pb_public/